if(window.location.pathname=="/st/WhatsApp-Plus-v7-35-apk")
{window.location.assign("https://get.abzinid.com/WhatsApp_Plus-v7-35-apk");}
if(window.location.pathname=="/st/WhatsApp-Plus-v7-25-apk")
{window.location.assign("https://www.up-4ever.org/z5tygvyrxx7e");}
if(window.location.pathname=="/st/GBWhatsApp-v6-89-apk")
{window.location.assign("https://get.abzinid.com/GBWhatsApp_v6-89-apk");}
if(window.location.pathname=="/st/GBWhatsApp-v7-25_Anti-Ban-apk")
{window.location.assign("https://get.abzinid.com/GBWhatsApp-Anti-Ban-v7-25-apk");}
if(window.location.pathname=="/st/GBWhatsApp-v7-35_Anti-Ban-apk")
{window.location.assign("https://www.up-4ever.org/qky5nye3d1hq");}
if(window.location.pathname=="/st/GBWhatsApp-v7-20_Anti-Ban-apk")
{window.location.assign("https://get.abzinid.com/GBWhatsApp_Anti-Ban-v7-20-apk");}
if(window.location.pathname=="/st/Gbwhatsapp-v7-00-apk")
{window.location.assign("https://www.up-4ever.org/vs03te98lv6t");}
if(window.location.pathname=="/st/PUBG-Momile-v0-13-0-apk")
{window.location.assign("http://www.mediafire.com/file/d48nawhekz8actx/PUBG-Momile-v0.13.0_abzinid.com.apk");}
if(window.location.pathname=="/st/PUBG-Momile-v0-3-0-main-obb-zip")
{window.location.assign("https://l.abzinid.com/PUBG-Momile-v0-3-0-main-obb-zip");}
if(window.location.pathname=="/st/PUBG-Momile-v0-13-0-main-obb-zip")
{window.location.assign("https://l.abzinid.com/PUBG-Momile-v0-13-0-main-obb-zip");}
if(window.location.pathname=="/st/http-injecotr-lite-apk")
{window.location.assign("https://www.up-4ever.org/atuevnzf1ve8");}
if(window.location.pathname=="/st/ehil-config-file1")
{window.location.assign("https://www.up-4ever.org/2mdu6s4zpe1c");}
if(window.location.pathname=="/st/ehil-config-file2")
{window.location.assign("https://www.up-4ever.org/t39liyckkbxm");}
if(window.location.pathname=="/st/lucky-Patcher-Official-8-4-1-apk")
{window.location.assign("https://www.up-4ever.org/dw65n6zrn7wq");}
if(window.location.pathname=="/st/lucky-patcher-mod-v8-3-8-zip")
{window.location.assign("https://www.up-4ever.org/fmothzzq10va");}
if(window.location.pathname=="/st/pes-2019-V3-2-0-apk")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21153&authkey=ABEwq7XlYZSoReQ");}
if(window.location.pathname=="/st/pes-2019-3-2-0-main-obb-zip")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21144&authkey=AMUyFSDkqPDu4oU");}
if(window.location.pathname=="/st/pes-2019-v3-2-0-patch-obb-zip")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21143&authkey=AOnvrqKQJsgJ23U");}
if(window.location.pathname=="/st/pes-2019-3-2-0-main-obb")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21146&authkey=AEnWVBCdjicq52k");}
if(window.location.pathname=="/st/dl-PES-2019-v3-2-0-patch-obb")
{window.location.assign("https://onedrive.live.com/download?cid=0EBD853649D6ACE3&resid=EBD853649D6ACE3%21109&authkey=AHEemrIJzy7y_pk");}
if(window.location.pathname=="/st/patch.303020001.jp.konami.pesam.ob")
{window.location.assign("https://www.mediafire.com/file/dlp29o54sl94nm2/patch.303020001.jp.konami.pesam.obb");}
if(window.location.pathname=="/st/Odin3-v3-11-1-Downloader")
{window.location.assign("https://www.up-4ever.org/bqppgvzohkb1");}
if(window.location.pathname=="/st/recovery-tar-md5")
{window.location.assign("https://www.up-4ever.org/cadzakhjbfyh");}
if(window.location.pathname=="/st/SuperSU-v2-79-zip")
{window.location.assign("https://www.up-4ever.org/z4xzsz3r7232");}
if(window.location.pathname=="/st/IDM-plus-v9-5")
{window.location.assign("https://www.up-4ever.org/7wphvwr31j5o");}
if(window.location.pathname=="/st/IDM-mod")
{window.location.assign("https://www.up-4ever.org/rwydtuh6d4nd");}
if(window.location.pathname=="/st/Asphalt8-Airborne-v4-0-2a")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21148&authkey=AAcjK3kcvUilfZU");}
if(window.location.pathname=="/st/Asphalt8-Airborne-mod-apk")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21147&authkey=AHnrJ6mJF1EK_to");}
if(window.location.pathname=="/st/textnow")
{window.location.assign("https://get.abzinid.com/dl-latest-TexTnow");}
if(window.location.pathname=="/st/dl-talkatone-v6-3-10-apk")
{window.location.assign("https://www.mediafire.com/file/bgu7d5xxxfatfk8/talkatone.apk");}
if(window.location.pathname=="/st/talkatone-v6-3-10-apk")
{window.location.assign("https://get.abzinid.com/dl-talkatone");}
if(window.location.pathname=="/st/TextPlus")
{window.location.assign("https://www.up-4ever.org/dc9ya7396sf4");}
if(window.location.pathname=="/st/DingTone-apk")
{window.location.assign("https://www.up-4ever.org/gdqfmfepcbzv");}
if(window.location.pathname=="/st/mirror-DingTone-apk")
{window.location.assign("https://bit.ly/DingTone-apk");}
if(window.location.pathname=="/st/latest-http-injector")
{window.location.assign("https://www.up-4ever.org/2jydj5pd7lud");}
if(window.location.pathname=="/st/sedc-ehi-config-usa")
{window.location.assign("https://www.up-4ever.org/4gn0i1pm5t5r");}
if(window.location.pathname=="/st/sedc-ehi-config-germany")
{window.location.assign("https://www.up-4ever.org/n8y6xihg05v1");}
if(window.location.pathname=="/st/sedc-ehi-singapore")
{window.location.assign("https://www.up-4ever.org/a23suqjb1hyh");}
if(window.location.pathname=="/st/sparkvpn")
{window.location.assign("https://www.up-4ever.org/i5jhzpc7g04f");}
if(window.location.pathname=="/st/sedc-spark-config")
{window.location.assign("https://www.up-4ever.org/g2nwnhq34nz1");}
if(window.location.pathname=="/st/sedc-spark-config-germany")
{window.location.assign("https://www.up-4ever.org/qukvttebp5v2");}
if(window.location.pathname=="/st/sedc-spark-config-singapore")
{window.location.assign("https://www.up-4ever.org/c65bxm8ti8od");}
if(window.location.pathname=="/st/snaptube-vip-apk")
{window.location.assign("https://get.abzinid.com/snaptube-VIP");}
if(window.location.pathname=="/st/PUBG_MOBILE_LITE_v0-14-0-apk")
{window.location.assign("https://www.mediafire.com/file/vijrnjcdi2uk399/PUBG_MOBILE_LITE_v0.14.0.apk");}
if(window.location.pathname=="/st/PUBG_MOBILE_LITE_0-14-0-obb")
{window.location.assign("https://www.mediafire.com/file/em750oi0xr5be19/PUBG_MOBILE_LITEv0.14.0.main%252Cobb.zip");}
if(window.location.pathname=="/st/PUBG-MOBILE-LITE-v0-12-0-apk")
{window.location.assign("https://www.mediafire.com/file/dx89zevqhgy1es2/PUBG-MOBILE-LITE-v0.12.0-b9580-abzinid.com.apk");}
if(window.location.pathname=="/st/PUBG-MOBILE-LITE-v0-12-0-main-obb-zip")
{window.location.assign("https://l.abzinid.com/PUBG-MOBILE-LITE-v0-12-0-main-obb-zip");}
if(window.location.pathname=="/st/Mercs-of-Boom-v2-0-20-apk")
{window.location.assign("https://get.abzinid.com/Mercs-of-Boom-apk");}
if(window.location.pathname=="/st/mirror-Mercs-of-Boom")
{window.location.assign("https://bit.ly/Mercs-of-Boom");}
if(window.location.pathname=="/st/ktr-opener")
{window.location.assign("https://www.up-4ever.org/ghdaiev2x21l");}
if(window.location.pathname=="/st/kpn-tunnel-revolution")
{window.location.assign("https://www.up-4ever.org/5joygbtosfo4");}
if(window.location.pathname=="/st/kpn-tunnel")
{window.location.assign("https://www.up-4ever.org/sdd14dml91rx");}
if(window.location.pathname=="/st/kpn-tunnel-ultimate")
{window.location.assign("https://www.up-4ever.org/jooltkugtwmp");}
if(window.location.pathname=="/st/xposed")
{window.location.assign("https://www.up-4ever.org/yiznx77go4bk");}
if(window.location.pathname=="/st/kingroot")
{window.location.assign("https://www.up-4ever.org/r3v5eujxfpc6");}
if(window.location.pathname=="/st/rootchecker")
{window.location.assign("https://www.up-4ever.org/5k8kpxphz2t6");}
if(window.location.pathname=="/st/setdns")
{window.location.assign("https://www.up-4ever.org/n5j25ywpyh1h");}
if(window.location.pathname=="/st/overridedns")
{window.location.assign("https://www.up-4ever.org/d1b6a1pjugf5");}
if(window.location.pathname=="/st/ehi-config-canada")
{window.location.assign("https://www.up-4ever.org/4tdp26aawh5b");}
if(window.location.pathname=="/st/ehi-config-uk")
{window.location.assign("https://www.up-4ever.org/zrqg78ww47p7");}
if(window.location.pathname=="/st/ehi-config-usa")
{window.location.assign("https://www.up-4ever.org/n4mm75ohho5o");}
if(window.location.pathname=="/st/kpn-config-usa")
{window.location.assign("https://www.up-4ever.org/2h218mphvbu0");}
if(window.location.pathname=="/st/spark-config-mtn-1")
{window.location.assign("https://www.up-4ever.org/3zkudxejkjyn");}
if(window.location.pathname=="/st/spark-config=mtn-2")
{window.location.assign("https://www.up-4ever.org/rxv0043js9lo");}
if(window.location.pathname=="/st/spark-config=mtn-3")
{window.location.assign("https://www.up-4ever.org/3d5jud1wtdfp");}
if(window.location.pathname=="/st/X-plorer")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21154&authkey=AH7RjFIo8ybvsIA");}
if(window.location.pathname=="/st/es-xplorer")
{window.location.assign("https://get.abzinid.com/ES-file-explorer");}
if(window.location.pathname=="/st/http-proxy-injector-pc")
{window.location.assign("https://get.abzinid.com/http-injector-for-pc");}
if(window.location.pathname=="/st/xposed-installer")
{window.location.assign("https://www.up-4ever.org/yiznx77go4bk");}
if(window.location.pathname=="/st/kpn-opener-v0-3-apk")
{window.location.assign("https://www.up-4ever.org/l1453utiwmzm");}
if(window.location.pathname=="/st/mobogram")
{window.location.assign("https://www.up-4ever.org/c7x642jzgdew");}
if(window.location.pathname=="/st/epro-opener-v0-3-6")
{window.location.assign("https://www.up-4ever.org/o7lj82f4g9w2");}
if(window.location.pathname=="/st/eproxy-nightly-v-2-7-29")
{window.location.assign("https://www.up-4ever.org/3s4mxm32ezy8");}
if(window.location.pathname=="/st/eproxy-v2-9-34")
{window.location.assign("https://www.up-4ever.org/ie4irc9tyaro");}
if(window.location.pathname=="/st/mobogram-one")
{window.location.assign("https://www.up-4ever.org/p0xa2c0a3lcc");}
if(window.location.pathname=="/st/mobogram-two")
{window.location.assign("https://www.up-4ever.org/l5o08ciayath");}
if(window.location.pathname=="/st/mobogram-three")
{window.location.assign("https://www.up-4ever.org/c7x642jzgdew");}
if(window.location.pathname=="/st/ehiopener48")
{window.location.assign("https://www.up-4ever.org/w3hflmi12iz9");}
if(window.location.pathname=="/st/injectotr341")
{window.location.assign("https://www.up-4ever.org/hx9cn1j62qa2");}
if(window.location.pathname=="/st/ehiopener47")
{window.location.assign("https://www.up-4ever.org/iers808rv9hj");}
if(window.location.pathname=="/st/injector430")
{window.location.assign("https://www.up-4ever.org/32u7c5uejuxl");}
if(window.location.pathname=="/st/EaseUS-MobiSaver-apk")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21156&authkey=APjhNgGVi5ntUFA");}
if(window.location.pathname=="/st/netify-vpn")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21150&authkey=ALCCOVniZscsQiQ");}
if(window.location.pathname=="/st/psyphon-pro-lite-handler")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21152&authkey=AOaPkJDt6q8HrRA");}
if(window.location.pathname=="/st/Psiphon82HandlerUI-apk")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21151&authkey=AKr3fiP4j891g_U");}
if(window.location.pathname=="/st/Ultrasurf-Handler-vpn")
{window.location.assign("https://onedrive.live.com/download?cid=55ECB69E9B6B670B&resid=55ECB69E9B6B670B%21149&authkey=ACjlf_dlTsXv62M");}
if(window.location.pathname=="/st/injector-43073-apk")
{window.location.assign("https://www.up-4ever.org/32u7c5uejuxl");}
if(window.location.pathname=="/st/ehiopener46")
{window.location.assign("https://www.up-4ever.org/9vzyrvar6lmp");}
if(window.location.pathname=="/st/injector42371")
{window.location.assign("https://www.up-4ever.org/1wkyr4jap4ic");}
if(window.location.pathname=="/st/ehiopener-unlocker")
{window.location.assign("https://www.up-4ever.org/hk3d6edaiar0");}
if(window.location.pathname=="/st/luckypatcher-apk")
{window.location.assign("https://www.up-4ever.org/3s6for4o1hhl");}
if(window.location.pathname=="/st/grand-theft-v1-07-apk")
{window.location.assign("https://www.up-4ever.org/ekkpkmppccj3");}
if(window.location.pathname=="/st/grand-theft-v1-07-zip")
{window.location.assign("https://get.abzinid.com/dl-grand-theft-v1-07-zip");}
if(window.location.pathname=="/st/Samsung-USB-Drivers")
{window.location.assign("https://www.up-4ever.org/b1hx22ap5v17");}
if(window.location.pathname=="/st/TWRP-S7582-tar-md5")
{window.location.assign("https://www.up-4ever.org/yhtj9xrgsy7x");}
if(window.location.pathname=="/st/WhatsApp-Plus-v8-00-apk")
{window.location.assign("https://get.abzinid.com/WhatsApp-Plus_v8-00-apk");}
if(window.location.pathname=="/st/GBWhatsApp-Pro-v8-00-apk")
{window.location.assign("https://get.abzinid.com/GBWhatsApp-Pro_v8-00-apk");}
if(window.location.pathname=="/st/dr-whatsapp-plus-8-00-apk")
{window.location.assign("https://www.mediafire.com/file/wzrybszxca910ws/WhatsApp_Plus_v8.00.apk");}
if(window.location.pathname=="/st/PUBG-Mobile-0-14-0-apk")
{window.location.assign("https://www.mediafire.com/file/vijrnjcdi2uk399/PUBG_MOBILE_LITE_v0.14.0.apk");}
if(window.location.pathname=="/st/PUBG.Mobile-v0-14-0-main-obb-zip")
{window.location.assign("https://www.mediafire.com/file/em750oi0xr5be19/PUBG_MOBILE_LITEv0.14.0.main%252Cobb.zip");}
if(window.location.pathname=="/st/dr-PUBG-Momile-v0-14-0-apk")
{window.location.assign("https://l.abzinid.com/PUBG-MOBILE-LITE-v0-12-0-apk");}
if(window.location.pathname=="/st/dr-PUBG-Momile-v0-14-0-main-obb-zip")
{window.location.assign("https://www.dropbox.com/s/b925ik0oy19osv4/PUBG.Mobile.v0.14.0.main.obb.zip?raw=1");}
if(window.location.pathname=="/st/Lolipop-Extreme-zip")
{window.location.assign("https://www.up-4ever.org/0i94uh37z703");}
if(window.location.pathname=="/st/preactivated-zip")
{window.location.assign("https://www.up-4ever.org/88eosd8ngdae");}
if(window.location.pathname=="/st/dls-19-ucl-apk")
{window.location.assign("https://get.abzinid.com/dls-19-ucl-apk");}
if(window.location.pathname=="/st/dsl-2019-obb-data-ucl-zip")
{window.location.assign("https://get.abzinid.com/dls-2019-ucl-obb-data-file-zip");}
if(window.location.pathname=="/st/dls-2019-ucl-data-file-zip")
{window.location.assign("https://get.abzinid.com/dls-2019-ucl-data-zip");}
if(window.location.pathname=="/st/Dream_League_Soccer_2018_v5-064_apk")
{window.location.assign("https://get.abzinid.com/Dream_League_Soccer_2018_82_v5-064_apk");}
if(window.location.pathname=="/st/Dream-League-main-82-obb")
{window.location.assign("https://get.abzinid.com/Dream-League-main-82-v5-064-obb-zip");}
if(window.location.pathname=="/st/Dream_League_Soccer_2018_v5-053_apk")
{window.location.assign("https://get.abzinid.com/Dream_League_Soccer_2018_v5-053-apk");}
if(window.location.pathname=="/st/Dream_league_main_59_obb_zip")
{window.location.assign("https://get.abzinid.com/Dream-League-main-59-obb-zip");}
if(window.location.pathname=="/st/dream_league_v6-13-109-apk")
{window.location.assign("https://get.abzinid.com/Dream_League_2019-109-v6-13-apk");}
if(window.location.pathname=="/st/dream_league_2019_109_obb_zip")
{window.location.assign("https://get.abzinid.com/Dream_league-2019_109-obb-zip");}
if(window.location.pathname=="/st/dream-league-2019-6-11-apk")
{window.location.assign("https://get.abzinid.com/Dream-League-2019-6-11-apk");}
if(window.location.pathname=="/st/dream-league-2019-main-104-obb-zip")
{window.location.assign("https://get.abzinid.com/Dream-League-2019-main-104-obb-zip");}
if(window.location.pathname=="/st/dream-league-2019-6-7-apk")
{window.location.assign("https://get.abzinid.com/Dream-league-Soccer-2019-v-6-07-apk");}
if(window.location.pathname=="/st/dream-league-main-98-obb-zip")
{window.location.assign("https://get.abzinid.com/Dream-League-main-98-obb-zip");}
if(window.location.pathname=="/st/PUBG_MOBILE_v0-15-0-apk")
{window.location.assign("https://get.abzinid.com/PUBG_MOBILE_v0-15-0-apk");}
if(window.location.pathname=="/st/PUBG-MOBILE-V0-15-0-obb-zip")
{window.location.assign("https://get.abzinid.com/PUBG-MOBILE-V0-15-0-obb-zip");}
if(window.location.pathname=="/st/Graphic-tool-for-Battleground-v4-5-1-apk")
{window.location.assign("https://get.abzinid.com/Graphic-tool-for-Battleground-v4-5-1-apk");}
